### PR TITLE
Make `matches()` return an iterator

### LINKED ISSUE #2: Make `matches()` return an iterator
`String#matchAll` returns an iterator, so the matching is lazy and you can stop it at any time.

The difficulty is ensuring it still times out. We may have to add something to `function-timeout` for this.

### PR DESCRIPTION
**Pull request by Richienb**
Breaking change

Fixes #2

### CODE REVIEW

**Comment by sindresorhus** [comment]
This makes the timeout apply to each element. When I opened the issue, I was thinking it should apply to the total iteration time. I'm interested in your thoughts on this.

**Comment by Richienb** [comment]
If the regex takes 10 milliseconds to run, it only takes 100 items to reach the default 1000 millisecond limit. With the system proposed in this PR, it makes the most of the data until it reaches an item that causes the regex to crash, though I'm not sure whether Regexes work like this.

Otherwise, we could just use `time-span` and add up the times between executions.

**Comment by sindresorhus** [comment]
I think the user would expect it to apply to the whole operation, not per match. This is consistent with the other methods. The timeout is not just useful for ReDoS, but also just passing too large of an input to an inefficient regex.

We could potentially also add a `matchTimeout` option.

**Comment by Richienb** [comment]
@sindresorhus did it

**Comment by sindresorhus** [comment]
Looks great

**Pull request merged**
